name: Version changes to the main branch

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  version-main-branch-changes:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: generate-app-token
        with:
          app-id: ${{ vars.APP_ID_WORKFLOW_DOC_CONTINUOUS_DELIVERY }}
          private-key: ${{ secrets.APP_KEY_WORKFLOW_DOC_CONTINUOUS_DELIVERY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate-app-token.outputs.token }}

      - name: Compute latest version
        id: get_latest_version
        run: |
          # Retrieve the latest git tag, as we will only be processing one delivery line.
          latest_version=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest version is $latest_version"
          echo "latest_version=$latest_version" >> "$GITHUB_OUTPUT"

      - name: Compute next version
        id: get_next_version
        run: |
          major=$(echo $latest_version | cut --delimiter=. --fields=1)
          minor=$(echo $latest_version | cut --delimiter=. --fields=2)
          patch=$(echo $latest_version | cut --delimiter=. --fields=3)

          is_new_major_version="false"

          change_type=$(git log -1 --pretty=%B | grep -oP '(?<=change-type:\s)\w+')
          if [ "$change_type" == "backward-compatible fixes" ]; then
            patch=$((patch+1))
          elif [ "$change_type" == "backward-compatible features" ]; then
            minor=$((minor+1))
          elif [ "$change_type" == "backward-incompatible" ]; then
            major_number=$(echo "$major" | cut --delimiter=v --fields=2)
            major="v$((major_number+1))"
            is_new_major_version="true"
            minor="0"
            patch="0"
          fi

          next_version="$major.$minor.$patch"
          echo "Next version is $next_version"

          echo "next_version=$next_version" >> "$GITHUB_OUTPUT"
          echo "is_new_major_version=$is_new_major_version" >> "$GITHUB_OUTPUT"
        env:
          latest_version: ${{ steps.get_latest_version.outputs.latest_version }}

      - name: Create reproducible tag
        run: |
          git config user.name "workflow-doc-continuous-delivery[bot]"
          git config user.email "workflow-doc-continuous-delivery[bot]@users.noreply.github.com"

          if git tag -a "$next_version" -m "$next_version"; then
            git push --follow-tags origin "$next_version"
          else
            echo "Failed to create tag $next_version, it probably already exists"
          fi

          if [ "$is_new_major_version" == "true"]; then
            major=$(echo $next_version | cut --delimiter=. --fields=1)
            git tag -a "$major" -m "$major" && git push --follow-tags origin "$major"
          fi
        env:
          next_version: "${{ steps.get_next_version.outputs.next_version }}"
          is_new_major_version: "${{ steps.get_next_version.outputs.is_new_major_version }}"
